env:
  commonjs: true
  shared-node-browser: true
  node: true
  es2021: true
  jest: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-await-in-loop: warn
  no-unreachable: warn
  indent:
    - error
    - tab
    - SwitchCase: 1
      outerIIFEBody: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - double
  semi:
    - error
    - always
  prefer-const:
    - warn

  '@typescript-eslint/no-inferrable-types':
    - warn
    - ignoreParameters: true
      ignoreProperties: true
  '@typescript-eslint/ban-ts-comment':
    - error
    - ts-ignore: 'allow-with-description'
