env:
  node: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
    - outerIIFEBody: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - double
  semi:
    - error
    - always
  prefer-const:
    - warn

  '@typescript-eslint/no-inferrable-types':
    - warn
    - ignoreParameters: true
      ignoreProperties: true
  '@typescript-eslint/ban-ts-comment':
    - error
    - ts-ignore: 'allow-with-description'
